/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as VerifyRouteImport } from "./routes/verify"
import { Route as ReviewerRouteImport } from "./routes/reviewer"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AttendeeRouteImport } from "./routes/attendee"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ReviewerIndexRouteImport } from "./routes/reviewer/index"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as InviteTokenRouteImport } from "./routes/invite.$token"
import { Route as AttendeeFormRouteImport } from "./routes/attendee/form"
import { Route as AdminUsersRouteImport } from "./routes/admin/users"
import { Route as AdminSubmissionsRouteImport } from "./routes/admin/submissions"
import { Route as AdminSettingsRouteImport } from "./routes/admin/settings"
import { Route as AdminInvitesRouteImport } from "./routes/admin/invites"
import { Route as SlugRegisterRouteImport } from "./routes/$slug/register"

const VerifyRoute = VerifyRouteImport.update({
  id: "/verify",
  path: "/verify",
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerRoute = ReviewerRouteImport.update({
  id: "/reviewer",
  path: "/reviewer",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeeRoute = AttendeeRouteImport.update({
  id: "/attendee",
  path: "/attendee",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerIndexRoute = ReviewerIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ReviewerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeeFormRoute = AttendeeFormRouteImport.update({
  id: "/form",
  path: "/form",
  getParentRoute: () => AttendeeRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: "/submissions",
  path: "/submissions",
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: "/invites",
  path: "/invites",
  getParentRoute: () => AdminRoute,
} as any)
const SlugRegisterRoute = SlugRegisterRouteImport.update({
  id: "/$slug/register",
  path: "/$slug/register",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/attendee": typeof AttendeeRouteWithChildren
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/reviewer": typeof ReviewerRouteWithChildren
  "/verify": typeof VerifyRoute
  "/$slug/register": typeof SlugRegisterRoute
  "/admin/invites": typeof AdminInvitesRoute
  "/admin/settings": typeof AdminSettingsRoute
  "/admin/submissions": typeof AdminSubmissionsRoute
  "/admin/users": typeof AdminUsersRoute
  "/attendee/form": typeof AttendeeFormRoute
  "/invite/$token": typeof InviteTokenRoute
  "/admin/": typeof AdminIndexRoute
  "/reviewer/": typeof ReviewerIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/attendee": typeof AttendeeRouteWithChildren
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/verify": typeof VerifyRoute
  "/$slug/register": typeof SlugRegisterRoute
  "/admin/invites": typeof AdminInvitesRoute
  "/admin/settings": typeof AdminSettingsRoute
  "/admin/submissions": typeof AdminSubmissionsRoute
  "/admin/users": typeof AdminUsersRoute
  "/attendee/form": typeof AttendeeFormRoute
  "/invite/$token": typeof InviteTokenRoute
  "/admin": typeof AdminIndexRoute
  "/reviewer": typeof ReviewerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/attendee": typeof AttendeeRouteWithChildren
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/reviewer": typeof ReviewerRouteWithChildren
  "/verify": typeof VerifyRoute
  "/$slug/register": typeof SlugRegisterRoute
  "/admin/invites": typeof AdminInvitesRoute
  "/admin/settings": typeof AdminSettingsRoute
  "/admin/submissions": typeof AdminSubmissionsRoute
  "/admin/users": typeof AdminUsersRoute
  "/attendee/form": typeof AttendeeFormRoute
  "/invite/$token": typeof InviteTokenRoute
  "/admin/": typeof AdminIndexRoute
  "/reviewer/": typeof ReviewerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/attendee"
    | "/login"
    | "/register"
    | "/reviewer"
    | "/verify"
    | "/$slug/register"
    | "/admin/invites"
    | "/admin/settings"
    | "/admin/submissions"
    | "/admin/users"
    | "/attendee/form"
    | "/invite/$token"
    | "/admin/"
    | "/reviewer/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/attendee"
    | "/login"
    | "/register"
    | "/verify"
    | "/$slug/register"
    | "/admin/invites"
    | "/admin/settings"
    | "/admin/submissions"
    | "/admin/users"
    | "/attendee/form"
    | "/invite/$token"
    | "/admin"
    | "/reviewer"
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/attendee"
    | "/login"
    | "/register"
    | "/reviewer"
    | "/verify"
    | "/$slug/register"
    | "/admin/invites"
    | "/admin/settings"
    | "/admin/submissions"
    | "/admin/users"
    | "/attendee/form"
    | "/invite/$token"
    | "/admin/"
    | "/reviewer/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AttendeeRoute: typeof AttendeeRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReviewerRoute: typeof ReviewerRouteWithChildren
  VerifyRoute: typeof VerifyRoute
  SlugRegisterRoute: typeof SlugRegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify": {
      id: "/verify"
      path: "/verify"
      fullPath: "/verify"
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reviewer": {
      id: "/reviewer"
      path: "/reviewer"
      fullPath: "/reviewer"
      preLoaderRoute: typeof ReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/attendee": {
      id: "/attendee"
      path: "/attendee"
      fullPath: "/attendee"
      preLoaderRoute: typeof AttendeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reviewer/": {
      id: "/reviewer/"
      path: "/"
      fullPath: "/reviewer/"
      preLoaderRoute: typeof ReviewerIndexRouteImport
      parentRoute: typeof ReviewerRoute
    }
    "/admin/": {
      id: "/admin/"
      path: "/"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    "/invite/$token": {
      id: "/invite/$token"
      path: "/invite/$token"
      fullPath: "/invite/$token"
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/attendee/form": {
      id: "/attendee/form"
      path: "/form"
      fullPath: "/attendee/form"
      preLoaderRoute: typeof AttendeeFormRouteImport
      parentRoute: typeof AttendeeRoute
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/submissions": {
      id: "/admin/submissions"
      path: "/submissions"
      fullPath: "/admin/submissions"
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/settings": {
      id: "/admin/settings"
      path: "/settings"
      fullPath: "/admin/settings"
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/invites": {
      id: "/admin/invites"
      path: "/invites"
      fullPath: "/admin/invites"
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof AdminRoute
    }
    "/$slug/register": {
      id: "/$slug/register"
      path: "/$slug/register"
      fullPath: "/$slug/register"
      preLoaderRoute: typeof SlugRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInvitesRoute: AdminInvitesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AttendeeRouteChildren {
  AttendeeFormRoute: typeof AttendeeFormRoute
}

const AttendeeRouteChildren: AttendeeRouteChildren = {
  AttendeeFormRoute: AttendeeFormRoute,
}

const AttendeeRouteWithChildren = AttendeeRoute._addFileChildren(
  AttendeeRouteChildren,
)

interface ReviewerRouteChildren {
  ReviewerIndexRoute: typeof ReviewerIndexRoute
}

const ReviewerRouteChildren: ReviewerRouteChildren = {
  ReviewerIndexRoute: ReviewerIndexRoute,
}

const ReviewerRouteWithChildren = ReviewerRoute._addFileChildren(
  ReviewerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AttendeeRoute: AttendeeRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReviewerRoute: ReviewerRouteWithChildren,
  VerifyRoute: VerifyRoute,
  SlugRegisterRoute: SlugRegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
